export const API_ENDPOINTS = {
  LOGIN: '/login',
  REGISTER: '/register',
  LOGOUT: '/logout',
  FORGET_PASSWORD: '/forget-password',
  CATEGORIES: 'https://hungry-hub-back-end-service.onrender.com/categories/',
  DIETARY: '/dietary.json',
  BRANDS: '/brands.json',
  PRODUCTS: '/products.json',
  PRODUCT: '/product.json',
  RELATED_PRODUCTS: '/related_products.json',
  BEST_SELLER_PRODUCTS: '/products_best_seller.json',
  BEST_SELLER_GROCERY_PRODUCTS:
    'https://hungry-hub-back-end-service.onrender.com/products/best-seller-products',
  POPULAR_PRODUCTS: 'https://hungry-hub-back-end-service.onrender.com/products/popular-products',
  COOKIES_PRODUCTS: '/products_cookies.json',
  CHIPS_PRODUCTS: '/products_chips.json',
  POPCORN_JERKY_PRODUCTS: '/products_popcorn_jerky.json',
  FRESH_VEGETABLES_PRODUCTS: '/products_fresh_vegetables.json',
  SEARCH: '/search.json',
  ORDERS: '/orders.json',
  ORDER: '/order.json',
  ORDER_STATUS: '/order-status.json',
  ADDRESS: '/address.json',
  PAYMENT: '/payment.json',
  CONTACT: '/contact.json',
  SHOP: '/shop.json',
  SHOPS: '/shops.json',
  WISHLIST: '/wishlist.json',
};
